rails-full-stack/config/routes.rb
Rails.application.routes.draw do
  get 'herbs' => 'herb#index', as: 'herbs'
  get 'herbs/new' => 'herb#new', as: 'new_herb'
  get 'herbs/:id' => 'herb#show', as: 'herb'
  post 'herbs' => 'herb#create'
  get 'herbs/:id/edit' => 'herb#edit', as: 'edit_herb'
  patch 'herbs/:id' => 'herb#update'
  root 'herb#index'
end

rails-full-stack/app/models/herb.rb
class Herb < ApplicationRecord
end

rails-full-stack/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-full-stack/app/controllers/herb_controller.rb
class HerbController < ApplicationController

  def index
    @herbs = Herb.all
  end

  def show
    @herb = Herb.find(params[:id])
  end

  def new
    @herb = Herb.new
  end

  def create
    @herb = Herb.create(herb_params)
    if @herb.valid?
      redirect_to herbs_path
    end
  end

  def edit
    @herb = Herb.find(params[:id])
  end

  def update
    @herb = Herb.find(params[:id])
    @herb.update(herb_params)
    if @herb.valid?
      redirect_to herb_path(@herb)
    else
      redirect_to edit_herbs_path
    end
  end

  # anything below this line cannot be called outside the scope of this class:
  private
  # strong params:
  def herb_params
    params.require(:herb).permit(:name, :watered)
  end

end

rails-full-stack/app/helpers/herb_helper.rb
module HerbHelper
end

rails-full-stack/app/views/herb/edit.html.erb
<h2>Update a New Herb</h2>

<%= form_with model: @herb do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name%>
  <br>
  <br>
  <%= form.label :watered %>
  <%= form.text_field :watered %>
  <br>
  <br>
  <%= form.submit 'Edit herb' %>
<% end %>
<br>
<%= link_to 'Back to All Herbs', herbs_path %>

rails-full-stack/app/views/herb/index.html.erb
<h1>Herb Garden App</h1>

<ul>
  <% @herbs.each do |herb| %>
    <li>
      <%= link_to herb.name, herb_path(herb) %>
    </li>
  <% end %>
</ul>
<br>
<%= link_to 'Add an Herb', new_herb_path %>

rails-full-stack/app/views/herb/new.html.erb
<h2>Create a New Herb</h2>

<%= form_with model: @herb do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name%>
  <br>
  <br>
  <%= form.label :watered %>
  <%= form.text_field :watered %>
  <br>
  <br>
  <%= form.submit 'Add herb' %>
<% end %>
<br>
<%= link_to 'Back to All Herbs', herbs_path %>

rails-full-stack/app/views/herb/show.html.erb
<h2>Herb Info</h2>

<br>
<p>Name of herb: <%= @herb.name %></p>
<br>
<p>Is watered: <%= @herb.watered %></p>
<br>
<%= link_to 'Back to All Herbs', herbs_path %>

<br>
<%= link_to 'Edit Herb', edit_herb_path(@herb) %>

rails-full-stack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFullStack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>